name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
 echo:
    name: Run Smoke UI autotests
    runs-on: ubuntu-latest
    steps:
      run: echo "The operating system on the runner is $env:RUNNER_OS."
