name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "The operating system on the runner is $env:RUNNER_OS."
      - run: echo ${{ github.event }}
      - run: echo "${{ github.event.pull_request.head.ref }}"     
      - run: echo $env.GITHUB_REPOSITORY
      - run: echo " Print a single environment variable (the commit SHA ) - ${{ github.sha }} "
      - run: echo "Print all environment variables"
      - run:  env
      - run: env.GITHUB_REPOSITORY
