name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo " Print a single environment variable (the commit SHA ) - ${{ github.sha }} "
      - run: echo "Print all environment variables"
      - run: env
      - run: echo $GITHUB_REPOSITORY
      - run: echo "${{env.GITHUB_REPOSITORY}}"

  feature-branch-deploy:
    name: Feature branch deployment
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: Serhii.PerepeliukAQA
          repo: hello-github-actions
          run: echo $repo
